---

- name: Include Ansible OS family variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Include Agent installation file
  include: install_agent.yml
  tags: [install_agent]

- name: Test for Agent Provisioned
  stat:
    path: /var/alertlogic/etc/host_key.pem
  register: agent_provisioned
  ignore_errors: True
  tags:
    - configure_al_agent
    - provision_al_agent

- name: Include Agent optional configuration file
  include: configure_agent.yml
  tags: [configure_al_agent]

- name: Include Agent Provisioning file
  include: provision_agent.yml
  tags: [provision_al_agent]

- name: Include configuration steps required for log collection in Linux
  include: configure_loggers.yml
  tags: [provision_al_agent]

- name: Include check for SELinux policy requirements
  include: selinux.yml
  tags: [selinux]

- name: Start the Alert Logic Agent service
  service:
    name: al-agent
    state: started
    enabled: yes
  tags: install_al_agent
  when: not al_agent_for_imaging
